/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Clases.recepcionista;
import Clases.ticket;
import Clases.viaje;
import Clases.cliente;
import Clases.persona;
import Clases.localidad;
import ConexionDB.Conectar;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import java.util.List;
/**
 *
 * @author ex1fernajo
 */
public class frmViajeAltaDialog extends java.awt.Dialog {

    /**
     * Creates new form frmViajeAltaDialog
     */
    
    private persona person = new persona();
    
    public frmViajeAltaDialog(java.awt.Frame parent, boolean modal, persona per) {
        super(parent, modal);
        initComponents();
         setLocationRelativeTo(null);
        person = per;
         CargarClientes();
         CargarLocalidadOrigen();
         CargarLocalidadDestino();
         
         lblRecpcionista.setText(person.getNombre());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtNumeroOrigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCalleDestino = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroDestino = new javax.swing.JTextField();
        cboClientes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboLocalidadOrigen = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboLocalidadDestino = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lblRecpcionista = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCalleOrigen = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel3.setText("Dirección Destino");

        txtNumeroOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroOrigenKeyTyped(evt);
            }
        });

        jLabel4.setText("Cliente :");

        txtCalleDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalleDestinoKeyTyped(evt);
            }
        });

        jLabel5.setText("Creado por :");

        jLabel6.setText("Calle :");

        txtNumeroDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDestinoKeyTyped(evt);
            }
        });

        cboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Numero :");

        cboLocalidadOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Localidad :");

        cboLocalidadDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Calle :");

        lblRecpcionista.setText("Recepcionista");

        jLabel10.setText("Numero :");

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel11.setText("Localidad :");

        jLabel1.setText("Generación de Viajes");

        jLabel2.setText("Dirección Origen");

        txtCalleOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalleOrigenKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel4)
                                .addGap(66, 66, 66)
                                .addComponent(cboClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboLocalidadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(66, 66, 66)
                                            .addComponent(jLabel2)
                                            .addGap(31, 31, 31))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNumeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(31, 31, 31)
                                            .addComponent(txtCalleOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboLocalidadDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNumeroDestino)
                                            .addComponent(txtCalleDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblRecpcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCalleOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNumeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboLocalidadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtCalleDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNumeroDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cboLocalidadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblRecpcionista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        // TODO add your handling code here:
        try {
            viaje v = new viaje();
            v.setCliente((cliente)cboClientes.getSelectedItem());
            v.setCalleOrigen(txtCalleOrigen.getText());
            v.setNumerOrigen(txtNumeroOrigen.getText());
            v.setCalleDestino(txtCalleDestino.getText());
            v.setNumeroDestino(txtNumeroDestino.getText());
            v.setLocalidadOrigen((localidad)cboLocalidadOrigen.getSelectedItem());
            v.setLocalidadDestino((localidad)cboLocalidadDestino.getSelectedItem());
            v.setRecepcionista((recepcionista)person);
            v.altaViaje();
            
            
            v = v.getUltimoViaje();
            
            
            ticket t = new ticket();
            t.setIdViaje(v.getIdViaje());
            t.generarTicket();
            
            
            lblMensaje.setText("Viaje Guardado!!");
         }
         catch (Exception e)
         {
             lblMensaje.setText("Ocurrio un ERROR intente nuevamente!!");
         }
               
    }//GEN-LAST:event_btnGuardarMousePressed
    
    private boolean Validar()
    {
        
        return true;
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCalleOrigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleOrigenKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
                        
          } 
    }//GEN-LAST:event_txtCalleOrigenKeyTyped

    private void txtCalleDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleDestinoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
        if(Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
        }
    }//GEN-LAST:event_txtCalleDestinoKeyTyped

    private void txtNumeroOrigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroOrigenKeyTyped
        // TODO add your handling code here:
            char c=evt.getKeyChar(); 
            if(Character.isLetter(c)) { 
              getToolkit().beep(); 
              
             evt.consume(); 
              
               
          } 
    }//GEN-LAST:event_txtNumeroOrigenKeyTyped

    private void txtNumeroDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDestinoKeyTyped
        // TODO add your handling code here:
           char c=evt.getKeyChar(); 
                 
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
            
              evt.consume(); 
              
               
          } 
    }//GEN-LAST:event_txtNumeroDestinoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmViajeAltaDialog dialog = new frmViajeAltaDialog(new java.awt.Frame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
       
    }
    /**
     * Cargo las localidades para el combo
     */
    public void CargarLocalidadOrigen()
    {
        Connection conn = null;
        Conectar cn = new Conectar();
        
        try {
            Class.forName(cn.getDriver()).newInstance();
            conn = DriverManager.getConnection(cn.getUrl(), cn.getDatabaseUserName(), cn.getDatabasePassword());
            CallableStatement statement = conn.prepareCall("SELECT [ID_LOCALIDAD]\n" +
                                                            "      ,[DESCRIPCION]\n" +
                                                            "  FROM [RemisJava].[dbo].[LOCALIDAD]");
            //statement.setString(1, txtUsuario.getText());
            
            boolean hadResults = statement.execute();
        
            int rowCount = 0;    
            while (hadResults) 
            {
                ResultSet resultSet = statement.getResultSet();
                
                List<localidad> locList = new ArrayList<localidad>();
                 
                 localidad loc;
                // process result set
                while (resultSet.next()) {
                    
                    loc = new localidad();
                    
                    rowCount++;
                    
                    loc.setId_localidad(Integer.parseInt(resultSet.getString("ID_LOCALIDAD")));
                    loc.setDescripcion(resultSet.getString("DESCRIPCION"));
                   
                    locList.add(loc);
                   
                }
                cboLocalidadOrigen.setModel(new DefaultComboBoxModel(locList.toArray()));
                hadResults = statement.getMoreResults();
                
            }
 
            statement.close();
            conn.close();
            
          
            
        } catch (Exception e) {
             lblMensaje.setText( e.getMessage());
            
          
        }
    }
    
    /**
     * Cargo las localidades para el combo
     */
    public void CargarLocalidadDestino()
    {
        Connection conn = null;
        Conectar cn = new Conectar();
        
        try {
            Class.forName(cn.getDriver()).newInstance();
            conn = DriverManager.getConnection(cn.getUrl(), cn.getDatabaseUserName(), cn.getDatabasePassword());
            CallableStatement statement = conn.prepareCall("SELECT [ID_LOCALIDAD]\n" +
                                                            "      ,[DESCRIPCION]\n" +
                                                            "  FROM [RemisJava].[dbo].[LOCALIDAD]");
            //statement.setString(1, txtUsuario.getText());
            
            boolean hadResults = statement.execute();
        
            int rowCount = 0;    
            while (hadResults) 
            {
                ResultSet resultSet = statement.getResultSet();
                
                //List<String> ls = new ArrayList<String>(); 
                 List<localidad> locList = new ArrayList<localidad>();
                 
                 localidad loc;
                // process result set
                while (resultSet.next()) {
                    
                    loc = new localidad();
                    
                    rowCount++;
                    
                    loc.setId_localidad(Integer.parseInt(resultSet.getString("ID_LOCALIDAD")));
                    loc.setDescripcion(resultSet.getString("DESCRIPCION"));
                   
                    locList.add(loc);
                   
                }
                cboLocalidadDestino.setModel(new DefaultComboBoxModel(locList.toArray()));
                hadResults = statement.getMoreResults();
                
            }
 
            statement.close();
            conn.close();
            
          
            
        } catch (Exception e) {
             lblMensaje.setText( e.getMessage());
            
          
        }
    }

    public void CargarClientes()
    {
        Connection conn = null;
        Conectar cn = new Conectar();
        
        try {
            Class.forName(cn.getDriver()).newInstance();
            conn = DriverManager.getConnection(cn.getUrl(), cn.getDatabaseUserName(), cn.getDatabasePassword());
            CallableStatement statement = conn.prepareCall("SELECT [ID_CLIENTE]\n" +
                                                            "      ,[NOMBRE]\n" +
                                                            "      ,[APELLIDO]\n" +
                                                            "      ,[FECHA_ALTA]\n" +
                                                            "  FROM [RemisJava].[dbo].[CLIENTE] " +
                                                            "where BAJA = 1" );
            //statement.setString(1, txtUsuario.getText());
            
            boolean hadResults = statement.execute();
        
            int rowCount = 0;    
            while (hadResults) 
            {
                ResultSet resultSet = statement.getResultSet();
                
                //List<String> ls = new ArrayList<String>(); 
                List<cliente> cliList = new ArrayList<cliente>();
                cliente cli;
                // process result set
                while (resultSet.next()) {
                    rowCount++;
                    
                    cli = new cliente();
                    cli.setApellido(resultSet.getString("APELLIDO"));
                    cli.setNombre(resultSet.getString("NOMBRE"));
                    cli.setCodCli(Integer.parseInt(resultSet.getString("ID_CLIENTE")));
                    
                    
//                    String id = resultSet.getString("ID_CLIENTE");
//                    String nombre = resultSet.getString("NOMBRE");
//                    String apellido = resultSet.getString("APELLIDO");
                  
                    //lblMensaje.setText("| " + nombre + " | " + apellido + " | ");
                    cliList.add(cli);
                    //ls.add(id + " " + nombre + " " + apellido);
                   
                }
                //cboClientes.setModel(new DefaultComboBoxModel(ls.toArray()));
                 cboClientes.setModel(new DefaultComboBoxModel(cliList.toArray()));
                hadResults = statement.getMoreResults();
                
            }
 
            statement.close();
            conn.close();
            
          
            
        } catch (Exception e) {
             lblMensaje.setText( e.getMessage());
            
          
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboClientes;
    private javax.swing.JComboBox<String> cboLocalidadDestino;
    private javax.swing.JComboBox<String> cboLocalidadOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblRecpcionista;
    private javax.swing.JTextField txtCalleDestino;
    private javax.swing.JTextField txtCalleOrigen;
    private javax.swing.JTextField txtNumeroDestino;
    private javax.swing.JTextField txtNumeroOrigen;
    // End of variables declaration//GEN-END:variables
}
