/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package remis;

/**
 *
 * @author ex1fernajo
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarRemis = new javax.swing.JMenuBar();
        jMenuRemis = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuClienteAlta = new javax.swing.JMenuItem();
        jMenuClienteBaja = new javax.swing.JMenuItem();
        jMenuClienteModificacion = new javax.swing.JMenuItem();
        jMenuChofer = new javax.swing.JMenu();
        jMenuChoferAlta = new javax.swing.JMenuItem();
        jMenuChoferBaja = new javax.swing.JMenuItem();
        jMenuChoferModificacion = new javax.swing.JMenuItem();
        jMenuAuto = new javax.swing.JMenu();
        jMenuAutoAlta = new javax.swing.JMenuItem();
        jMenuAutoBaja = new javax.swing.JMenuItem();
        jMenuAutoModificacion = new javax.swing.JMenuItem();
        jMenuViaje = new javax.swing.JMenu();
        jMenuViajeAlta = new javax.swing.JMenuItem();
        jMenuViajeModificacion = new javax.swing.JMenuItem();
        jMenuTickets = new javax.swing.JMenu();
        jMenuTicketsListado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuRemis.setText("File");

        jMenuItemSalir.setText("Salir");
        jMenuRemis.add(jMenuItemSalir);

        jMenuBarRemis.add(jMenuRemis);

        jMenuCliente.setText("Cliente");

        jMenuClienteAlta.setText("Alta");
        jMenuCliente.add(jMenuClienteAlta);

        jMenuClienteBaja.setText("Baja");
        jMenuCliente.add(jMenuClienteBaja);

        jMenuClienteModificacion.setText("Modificación");
        jMenuCliente.add(jMenuClienteModificacion);

        jMenuBarRemis.add(jMenuCliente);

        jMenuChofer.setText("Chofer");

        jMenuChoferAlta.setText("Alta");
        jMenuChofer.add(jMenuChoferAlta);

        jMenuChoferBaja.setText("Baja");
        jMenuChofer.add(jMenuChoferBaja);

        jMenuChoferModificacion.setText("Modificación");
        jMenuChofer.add(jMenuChoferModificacion);

        jMenuBarRemis.add(jMenuChofer);

        jMenuAuto.setText("Auto");

        jMenuAutoAlta.setText("Alta");
        jMenuAuto.add(jMenuAutoAlta);

        jMenuAutoBaja.setText("Baja");
        jMenuAuto.add(jMenuAutoBaja);

        jMenuAutoModificacion.setText("Modificación");
        jMenuAuto.add(jMenuAutoModificacion);

        jMenuBarRemis.add(jMenuAuto);

        jMenuViaje.setText("Viajes");

        jMenuViajeAlta.setText("Alta");
        jMenuViaje.add(jMenuViajeAlta);

        jMenuViajeModificacion.setText("Modificación");
        jMenuViaje.add(jMenuViajeModificacion);

        jMenuBarRemis.add(jMenuViaje);

        jMenuTickets.setText("Tickets");

        jMenuTicketsListado.setText("Listado");
        jMenuTickets.add(jMenuTicketsListado);

        jMenuBarRemis.add(jMenuTickets);

        setJMenuBar(jMenuBarRemis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAuto;
    private javax.swing.JMenuItem jMenuAutoAlta;
    private javax.swing.JMenuItem jMenuAutoBaja;
    private javax.swing.JMenuItem jMenuAutoModificacion;
    private javax.swing.JMenuBar jMenuBarRemis;
    private javax.swing.JMenu jMenuChofer;
    private javax.swing.JMenuItem jMenuChoferAlta;
    private javax.swing.JMenuItem jMenuChoferBaja;
    private javax.swing.JMenuItem jMenuChoferModificacion;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuClienteAlta;
    private javax.swing.JMenuItem jMenuClienteBaja;
    private javax.swing.JMenuItem jMenuClienteModificacion;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuRemis;
    private javax.swing.JMenu jMenuTickets;
    private javax.swing.JMenuItem jMenuTicketsListado;
    private javax.swing.JMenu jMenuViaje;
    private javax.swing.JMenuItem jMenuViajeAlta;
    private javax.swing.JMenuItem jMenuViajeModificacion;
    // End of variables declaration//GEN-END:variables
}
