/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package remis;

/**
 *
 * @author ex1fernajo
 */
public class frmMenu extends javax.swing.JFrame {

    
    /**
     * Creates new form frmMenu
     */

    private persona person = new persona();
    
    public frmMenu( ) {
        initComponents();
      
    }
        public frmMenu(persona per ) {
            initComponents();
            
            person = per; 
            jLabel1.setText("Bienvenido " + person.getNombre() + " " + person.getApellido()); 
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBarRemis = new javax.swing.JMenuBar();
        jMenuRemis = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuClienteAlta = new javax.swing.JMenuItem();
        jMenuClienteBaja = new javax.swing.JMenuItem();
        jMenuClienteModificacion = new javax.swing.JMenuItem();
        jMenuChofer = new javax.swing.JMenu();
        jMenuChoferAlta = new javax.swing.JMenuItem();
        jMenuChoferBaja = new javax.swing.JMenuItem();
        jMenuChoferModificacion = new javax.swing.JMenuItem();
        jMenuAuto = new javax.swing.JMenu();
        jMenuAutoAlta = new javax.swing.JMenuItem();
        jMenuAutoBaja = new javax.swing.JMenuItem();
        jMenuAutoModificacion = new javax.swing.JMenuItem();
        jMenuViaje = new javax.swing.JMenu();
        jMenuViajeAlta = new javax.swing.JMenuItem();
        jMenuViajeModificacion = new javax.swing.JMenuItem();
        jMenuTickets = new javax.swing.JMenu();
        jMenuTicketsListado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jMenuRemis.setText("File");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemSalirMousePressed(evt);
            }
        });
        jMenuRemis.add(jMenuItemSalir);

        jMenuBarRemis.add(jMenuRemis);

        jMenuCliente.setText("Cliente");

        jMenuClienteAlta.setText("Alta");
        jMenuClienteAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteAltaActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuClienteAlta);

        jMenuClienteBaja.setText("Baja");
        jMenuClienteBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteBajaActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuClienteBaja);

        jMenuClienteModificacion.setText("Modificación");
        jMenuClienteModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteModificacionActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuClienteModificacion);

        jMenuBarRemis.add(jMenuCliente);

        jMenuChofer.setText("Chofer");

        jMenuChoferAlta.setText("Alta");
        jMenuChoferAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuChoferAltaMousePressed(evt);
            }
        });
        jMenuChofer.add(jMenuChoferAlta);

        jMenuChoferBaja.setText("Baja");
        jMenuChoferBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuChoferBajaMousePressed(evt);
            }
        });
        jMenuChofer.add(jMenuChoferBaja);

        jMenuChoferModificacion.setText("Modificación");
        jMenuChoferModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuChoferModificacionMousePressed(evt);
            }
        });
        jMenuChofer.add(jMenuChoferModificacion);

        jMenuBarRemis.add(jMenuChofer);

        jMenuAuto.setText("Auto");

        jMenuAutoAlta.setText("Alta");
        jMenuAutoAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuAutoAltaMouseReleased(evt);
            }
        });
        jMenuAuto.add(jMenuAutoAlta);

        jMenuAutoBaja.setText("Baja");
        jMenuAutoBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuAutoBajaMouseReleased(evt);
            }
        });
        jMenuAuto.add(jMenuAutoBaja);

        jMenuAutoModificacion.setText("Modificación");
        jMenuAutoModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAutoModificacionActionPerformed(evt);
            }
        });
        jMenuAuto.add(jMenuAutoModificacion);

        jMenuBarRemis.add(jMenuAuto);

        jMenuViaje.setText("Viajes");

        jMenuViajeAlta.setText("Alta");
        jMenuViajeAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuViajeAltaMousePressed(evt);
            }
        });
        jMenuViaje.add(jMenuViajeAlta);

        jMenuViajeModificacion.setText("Modificación");
        jMenuViajeModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuViajeModificacionMousePressed(evt);
            }
        });
        jMenuViaje.add(jMenuViajeModificacion);

        jMenuBarRemis.add(jMenuViaje);

        jMenuTickets.setText("Tickets");

        jMenuTicketsListado.setText("Listado");
        jMenuTicketsListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuTicketsListadoMousePressed(evt);
            }
        });
        jMenuTickets.add(jMenuTicketsListado);

        jMenuBarRemis.add(jMenuTickets);

        setJMenuBar(jMenuBarRemis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(616, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAutoAltaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAutoAltaMouseReleased
        // TODO add your handling code here:
        frmAutoAltaDialog frmAuto = new  frmAutoAltaDialog(this,true);
        frmAuto.setVisible(true);
    }//GEN-LAST:event_jMenuAutoAltaMouseReleased

    private void jMenuAutoBajaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAutoBajaMouseReleased
        frmAutoBajaDialog autoBaja = new frmAutoBajaDialog(this, true);
        autoBaja.setVisible(true);// TODO add your handling code here:

    }//GEN-LAST:event_jMenuAutoBajaMouseReleased

    private void jMenuViajeAltaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuViajeAltaMousePressed
        // TODO add your handling code here:
        frmViajeAltaDialog viajeAlta = new frmViajeAltaDialog(this, true, person);
        viajeAlta.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuViajeAltaMousePressed

    private void jMenuViajeModificacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuViajeModificacionMousePressed
        // TODO add your handling code here:
        frmViajeModificaciónDialog viajeModifucacion = new frmViajeModificaciónDialog(this, true);
        viajeModifucacion.setVisible(true);
        
    }//GEN-LAST:event_jMenuViajeModificacionMousePressed

    private void jMenuTicketsListadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTicketsListadoMousePressed
        // TODO add your handling code here:
           frmTicketListadoDialog ticketlist = new frmTicketListadoDialog(this,true);
        ticketlist.setVisible(true);
    }//GEN-LAST:event_jMenuTicketsListadoMousePressed

    private void jMenuAutoModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAutoModificacionActionPerformed
                // TODO add your handling code here:
           frmAutoModificacionDialog autoModificacion = new frmAutoModificacionDialog(this,true);
        autoModificacion.setVisible(true);
    }//GEN-LAST:event_jMenuAutoModificacionActionPerformed

    private void jMenuItemSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemSalirMousePressed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jMenuItemSalirMousePressed

    private void jMenuChoferBajaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuChoferBajaMousePressed
        // TODO add your handling code here:
            frmChoferBajaDialog choferModificacion = new frmChoferBajaDialog(this,true);
        choferModificacion.setVisible(true);
    }//GEN-LAST:event_jMenuChoferBajaMousePressed

    private void jMenuChoferAltaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuChoferAltaMousePressed
        // TODO add your handling code here:
        frmChoferAltaDialog choferAlta = new frmChoferAltaDialog(this, true);
        choferAlta.setVisible(true);
    }//GEN-LAST:event_jMenuChoferAltaMousePressed

    private void jMenuChoferModificacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuChoferModificacionMousePressed
        // TODO add your handling code here:
        frmChoferModificacionDialog choferModificacion = new frmChoferModificacionDialog(this, true);
        choferModificacion.setVisible(true);
    }//GEN-LAST:event_jMenuChoferModificacionMousePressed

    private void jMenuClienteAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteAltaActionPerformed
        // TODO add your handling code here:
        frmClienteAltaDialog clienteAlta = new frmClienteAltaDialog(this,true);
        clienteAlta.setVisible(true);
                
    }//GEN-LAST:event_jMenuClienteAltaActionPerformed

    private void jMenuClienteBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteBajaActionPerformed
        // TODO add your handling code here:
        frmClienteBajaDialog clienteBaja = new frmClienteBajaDialog(this,true);
        clienteBaja.setVisible(true);
    }//GEN-LAST:event_jMenuClienteBajaActionPerformed

    private void jMenuClienteModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteModificacionActionPerformed
        // TODO add your handling code here:
        frmClienteModificacionDialog clienteModelo = new frmClienteModificacionDialog(this,true);
        clienteModelo.setVisible(true);
    }//GEN-LAST:event_jMenuClienteModificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
           
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAuto;
    private javax.swing.JMenuItem jMenuAutoAlta;
    private javax.swing.JMenuItem jMenuAutoBaja;
    private javax.swing.JMenuItem jMenuAutoModificacion;
    private javax.swing.JMenuBar jMenuBarRemis;
    private javax.swing.JMenu jMenuChofer;
    private javax.swing.JMenuItem jMenuChoferAlta;
    private javax.swing.JMenuItem jMenuChoferBaja;
    private javax.swing.JMenuItem jMenuChoferModificacion;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuClienteAlta;
    private javax.swing.JMenuItem jMenuClienteBaja;
    private javax.swing.JMenuItem jMenuClienteModificacion;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuRemis;
    private javax.swing.JMenu jMenuTickets;
    private javax.swing.JMenuItem jMenuTicketsListado;
    private javax.swing.JMenu jMenuViaje;
    private javax.swing.JMenuItem jMenuViajeAlta;
    private javax.swing.JMenuItem jMenuViajeModificacion;
    // End of variables declaration//GEN-END:variables
}
